// Global
export const SET_USER_CONTEXT = "SET_USER_CONTEXT";
export const TOGGLE_VERIFY_MODAL = "TOGGLE_VERIFY_MODAL";

// User
export const SET_CURRENT_CONTEXT = "SET_CURRENT_CONTEXT";

// Course
export const SET_COURSES_LIST = "SET_COURSES_LIST";